version: "3"

services:
  gateway:
    image: apiteamdevops/echo-server-gateway:latest
    volumes:
      - gateway:/etc/resty-auto-ssl
    restart: always
    environment:
      ALLOWED_DOMAINS: echo.apiteam.cloud
    ports:
      - "80:80"
      - "443:443"
  echo:
    image: apiteamdevops/echo-server:latest
    restart: always

volumes:
  gateway:
    driver: local
